version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run tests-chrome
    volumes:
      - ./playwright-report/:/app/playwright-report/
